---
# if http/https not specified, defaults to https
# if you put http here, it will try verify=false, not to check certs
host: "https://bookstack.mydomain.org"
# You could optionally set the bookstack token_id and token_secret here instead of env
# If using env vars instead you can omit/comment out this section
credentials:
    # set here or as env variable, BOOKSTACK_TOKEN_ID
    # env var takes precedence over below
    token_id: ""
    # set here or as env variable, BOOKSTACK_TOKEN_SECRET
    # env var takes precedence over below
    token_secret: ""
# additional headers to add, examples below
# if not required, you can omit/comment out
additional_headers:
  test: "test"
  test2: "test2"
  User-Agent: "test-agent"
# supported formats from bookstack below
# specify one or more
formats:
  - markdown
  - html
  - pdf
  - plaintext
# directory to export to
# relative or full path
output_path: "bkps/"
# optional export of metadata about the page in a json file
# this metadata contains general information about the page
# like: last update, owner, revision count, etc.
# omit this or set to false if not needed
export_meta: true
# optional if specified exporter can delete older archives
# valid values are:
# set to -1 if you want to delete all archives after each run
# - this is useful if you only want to upload to object storage
# set to 1+ if you want to retain a certain number of archives
# set to 0 or comment out section if you want no action done
keep_last: 5
