# needs: [tests]  # require tests to pass before deploy runs

name: Build and Push

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '**' # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  docker_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Store the version, stripping any v-prefix
    - name: Write release version
      run: |
        TAG=${{ github.ref_name }}
        echo "VERSION=${TAG#v}" >> $GITHUB_ENV
        echo Version: $VERSION
    - name: Login to Dockerhub
      run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Prepare Makefile
      run: sed -i 's/^IMAGE_TAG=[^ ]*/IMAGE_TAG=${VERSION}/' Makefile
    - name: Build the Docker image
      run: make docker_build
    - name: Push Docker image
      run: make docker_push
  pypi_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Write release version
      run: |
        TAG=${{ github.ref_name }}
        echo "VERSION=${TAG#v}" >> $GITHUB_ENV
        echo Version: $VERSION
    - name: Update Release tag
      run: sed -i 's/^version = [^ ]*/version = ${VERSION}}/' setup.cfg
    - name: Build package
      run: make build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}